### ISSUE TITLE
allow for search of multiple keywords

### ISSUE THREAD

**Issue by kgashok** [rrkishoreraj/Bitly-Crawler-App-using-JavaScript#10]
Adopt the map-reduce paradigm in the implementation code. 

![screenshot 2018-12-21 at 22 18 02](https://user-images.githubusercontent.com/2399010/50353511-7fca0c00-056e-11e9-9c8e-4e139b94ec2c.png)

**Comment by kgashok** [comment]
Also, see if you can use a pause in the keystrokes to trigger search, instead of a space bar as implemented in the Elm Project - https://github.com/kgashok/elm-for-bitly/issues/39

**Comment by kgashok** [comment]
![screenshot 2018-12-22 at 01 29 17](https://user-images.githubusercontent.com/2399010/50361296-11467780-0589-11e9-86e8-0b1e6648f3e1.png)

**Comment by kgashok** [comment]
Must change the logic to use the more efficient `List.all` and `List.any`

**Comment by kgashok** [comment]
My code now further simplified (not to use map-reduce) to be more efficient. 

![screenshot 2018-12-24 at 17 57 57](https://user-images.githubusercontent.com/2399010/50399469-ade56100-07a5-11e9-9a09-f7c36cee4ac5.png)

**Comment by kgashok** [comment]
Further refactoring leads to simpler code: 
![screenshot 2018-12-24 at 22 33 35](https://user-images.githubusercontent.com/2399010/50404298-442c7d80-07cc-11e9-9262-f2f54ca2ddaf.png)

**Comment by kgashok** [comment]
Why not adopt different strategy - https://24ways.org/2018/fast-autocomplete-search-for-your-website/

**Comment by kgashok** [comment]
![screenshot 2019-02-21 at 14 34 51](https://user-images.githubusercontent.com/2399010/53156728-04c0b880-35e6-11e9-84a6-32a619723881.png)

Redundant links?

**Comment by rrkishoreraj** [comment]
No, sir. The **Test-file.json** intentionally contains redundant links. It is been created by copying all the links in **Links.json** (which contains **35links**) **143 times** (which gives the total of **5005 links**). And  that's why it prints **143 Matches Found!!!** when it's been searched as **python**, sir.

![image](https://user-images.githubusercontent.com/29670674/53236339-107daf00-36ba-11e9-8f54-ea3166238984.png)
